config/routes.rb
Rails.application.routes.draw do
  resources :experiences
#  get 'users/show'

  devise_for :users
  
  root to: "dashboard#index"
  get 'dashboard/index'
  get 'dashboard/page1'
  get 'dashboard/page2'
  
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :t_number, :college, :department, :rank, :rank_date, :tenure_date, :email, :password) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :t_number, :college, :department, :rank, :rank_date, :tenure_date, :email, :password, :password_confirmation, :current_password) }
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def page1 # experiences
    @exp = Experience.where("owner = ?", current_user.id)
  end

  def page2
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
    def bootstrap_version
        # Replace with most recent version
        "3.3.7"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<br/>
<%= link_to "Work Experience", { :controller => :dashboard, :action => :page1 } %>

app/views/dashboard/page1.html.erb
<h1>Experiences</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Company</th>
      <th>Title</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody id = "experienceList">
    <% @exp.each do |experience| %>
      <tr>
        <td data-toggle="modal" data-target="#myModal"><%= experience.start_date %></td>
        <td data-toggle="modal" data-target="#myModal"><%= experience.end_date %></td>
        <td data-toggle="modal" data-target="#myModal"><%= experience.name %></td>
        <td data-toggle="modal" data-target="#myModal"><%= experience.description %></td>
        <!--td>
        </td-->
        <td><%= link_to 'Edit', edit_experience_path(experience) %>
                    <span class="glyphicon glyphicon-edit"></span> 
        </td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %>
            <span class="glyphicon glyphicon-remove"></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Hello</h4>
      </div>
      <div class="modal-body" id="myModalBody">
        World
      </div>
    </div>
  </div>
</div>

app/views/dashboard/page2.html.erb
<h1>Dashboard#page2</h1>
<p>Find me in app/views/dashboard/page2.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment 08</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => false %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container-fluid">
      	<div class="row">
      		<div class="col-md-12">
      			<nav class="navbar navbar-default" role="navigation">
      				<div class="navbar-header">
      					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      					</button> 
      					<%= link_to root_path, { :class => "navbar-brand"} do %>
      					   <i class="glyphicon glyphicon-home"></i> Home
      					<% end %>
      				</div>
      				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      					<ul class="nav navbar-nav">
                    <% if user_signed_in? %>
      						<li>
      						  <%= link_to "Experiences", dashboard_page1_path %>
      						</li>
                    <% end %>      					    
      					</ul>
                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                    <li>
                      <%= link_to edit_user_registration_path do %>
                         <i class="glyphicon glyphicon-cog"></i>
                      <% end %>
                    </li>
                    <% end %>      					    
                    <li>
                    <% if user_signed_in? %>
                        <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                    <% else %>
                        <%= link_to "Login", new_user_session_path %>
                    <% end %>      					    
       					    </li>
      					</ul>
      				</div>
      			</nav>
      		</div>

      	</div>
      
      <% if notice %>
      <p class="notice">
        <div class="alert alert-info alert-dismissable">
           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
           <%= notice %>
        </div>
      </p>
      <% end %>
      <%= yield %>
      </div>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user.first_name %>